name: Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  KS_RELEASE_CHANNEL: nightly
  NIGHTLY_BUILD: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: print latest_commit
        run: echo ${{ github.sha }}

      - name: Select NodeJS version
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"

      - name: Enable Corepack
        run: |
          corepack enable
          yarn config set enableGlobalCache false

      - name: Build
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb
          mkdir $HOME/.ssh
          echo "Host *.hyx3179.com" > $HOME/.ssh/config
          echo "  ProxyCommand cloudflared access ssh --hostname %h" >> $HOME/.ssh/config
          export RELEASE_VERSION=$(node version.cjs)
          make userscript
          mkdir ./public
          cp ./output/kitten-scientists*.min.user.js ./public/kitten-scientists.user.js
          echo {\"KSbuildRevision\":\"${RELEASE_VERSION}\"} > ./public/ks.version.json

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
