name: Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Select NodeJS version
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"

      - name: Build
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb
          mkdir $HOME/.ssh
          echo "Host *.hyx3179.com" > $HOME/.ssh/config
          echo "  ProxyCommand cloudflared access ssh --hostname %h" >> $HOME/.ssh/config
          npm i -g google-closure-compiler
          yarn kitten-scientists:release
          mkdir ./public
          google-closure-compiler --js ./packages/kitten-scientists/output/kitten-scientists*.user.js --js_output_file ./public/kitten-scientists.user.js
          wget -q https://${DEPLOY_URL}/scientists/ks.version.json -O ./public/ks.version.json
          node generate-buildver.js

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
